name: Check US visa status

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
  push:
    branches:
      - main

jobs:
  check_visa:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Restore visa state
      uses: actions/cache@v3
      with:
        path: |
          ./visa_state_*.json
        key: visa-state-cache-v1-${{ hashFiles('visa_state_*.json') }}
        restore-keys: |
          visa-state-cache-v1-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright resend ddddocr
        playwright install chromium
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Run script
      env: # 在这里添加环境变量
        VISA_CASE_NUMBER: ${{ secrets.VISA_CASE_NUMBER }}
        PASSPORT_NUMBER: ${{ secrets.PASSPORT_NUMBER }}
        SURNAME: ${{ secrets.SURNAME }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        SENDER_ADDRESS: ${{ secrets.SENDER_ADDRESS }}
        # 可选：如果邮件接收者也设为 secret
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        xvfb-run python check_visa.py

    - name: Save visa state
      uses: actions/cache@v3
      with:
        path: |
          ./visa_state_*.json
        key: visa-state-cache-v1-${{ hashFiles('visa_state_*.json') }}
        restore-keys: |
          visa-state-cache-v1-
